VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "ubuntu/trusty64"
   config.vm.network "private_network", ip: "25.25.25.2"
   config.vm.synced_folder "/home/trinirya/workspace/src/space-invasion/sandbox/my-dev-vm/data", "/home/vagrant"
   # config.vm.provision :shell, path: "bootstrap.sh"
   # config.vm.network :forwarded_port, host: 4567, guest: 80
end
